import React from 'react'
export default function Head() {
  console.log()

  return (
    <>
      <title>Create Next App2</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </>
  )
}
