#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling your project before committing👷‍♂️🏗️'
echo 'please be patient, this may take a while...'

# Check ESLint Standards
yarn lint ||
(
    echo '🔨❌ 코드에 문제가 있습니다. linter 확인 🔨❌ yarn lint 실행, 변경 사항 추가 및 다시 커밋 시도.';
    false;
)









echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'

npx lint-staged
